# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js build

on:
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn
      
      - name: Build
        run: |
          yarn build
          cd dist && patch < ..\filters-import.patch && cd ..
          yarn build-pkg
          yarn build-node

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/*
          tags: true
          draft: false
          overwrite: true
